config/routes.rb
Rails.application.routes.draw do
  resources :results
  resources :subjects
  resources :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/result.rb
# == Schema Information
#
# Table name: results
#
#  id         :integer          not null, primary key
#  score      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  subject_id :integer
#  student_id :integer
#

class Result < ApplicationRecord
  belongs_to :student, optional: true, :foreign_key => "student_id" # got to make a foreign key in order to use
  belongs_to :subject, optional: true, :foreign_key => "subject_id"
end

app/models/student.rb
# == Schema Information
#
# Table name: students
#
#  id           :integer          not null, primary key
#  name         :string
#  surname      :string
#  student_code :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Student < ApplicationRecord
  has_many :results

  def student_name
    	return "#{self.name} (#{self.surname})"
  end
end

app/models/subject.rb
# == Schema Information
#
# Table name: subjects
#
#  id           :integer          not null, primary key
#  name         :string
#  subject_code :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Subject < ApplicationRecord
  has_many :results

  def subject_name # just a class name in order to use it
    	return "#{self.name} (#{self.subject_code})"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:show, :edit, :update, :destroy]

  # GET /results
  # GET /results.json
  def index
    @result_english = Result.where(subject_id: '1').order('score ASC') # a little bit weird here, as got to manually input the ID for
    @result_math = Result.where(subject_id: '2').order('score ASC') # subject in order to separate, maybe a better way though.
  end

  # GET /results/1
  # GET /results/1.json
  def show
  end

  # GET /results/new
  def new
    @result = Result.new # retrieve the students to make a new result for them
    @students = Student.all
    @subjects = Subject.all
  end

  # GET /results/1/edit
  def edit
  end

  # POST /results
  # POST /results.json
  def create

    @result = Result.new(result_params)
    @students = Student.where(id: @result.student_id) #make sure the id is the students id
    @subjects = Subject.where(id: @result.subject_id) #makes sure the id is the subject id
    respond_to do |format|
      if @result.save
        format.html { redirect_to @result, notice: 'Result was successfully created.' }
        format.json { render :show, status: :created, location: @result }
      else
        format.html { render :new }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /results/1
  # PATCH/PUT /results/1.json
  def update
    respond_to do |format|
      if @result.update(result_params)
        format.html { redirect_to @result, notice: 'Result was successfully updated.' }
        format.json { render :show, status: :ok, location: @result }
      else
        format.html { render :edit }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result.destroy
    respond_to do |format|
      format.html { redirect_to results_url, notice: 'Result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.require(:result).permit(:score, :subject_id, :student_id)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :surname, :student_code)
    end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:name, :subject_code)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/layouts/_header.html.erb
  <div class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Ideractive Test</a>
      </div>
      <div class="navbar-collapse collapse navbar-responsive-collapse">
          <!-- <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only"></span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">Disabled</a>
            </li>
          </ul> -->
        <ul class="nav navbar-nav navbar-left">
          <li class="nav-item active">
            <a class="nav-link" href="/students">Students<span class="sr-only"></span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/subjects">Subjects</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/results">Results</a>
          </li>
        </ul>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ideractive Test</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div id="main-container" class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/results/_form.html.erb
<%= form_with(model: result, local: true) do |form| %>
  <% if result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :score %>
    <%= form.text_field :score, id: :result_score %>
  </div>

  <div class="form-group">
      <label for="select" class="col-lg-2 control-label">Select Student</label>
      <div class="col-lg-10">
        <select class="form-control" id="select" <%= form.select :student_id, options_for_select(@students.map{|s| [s.student_name,s.id]}) %>
  </div>

  <div class="form-group">
      <label for="select" class="col-lg-2 control-label">Select Subject</label>
      <div class="col-lg-10">
        <select class="form-control" id="select" <%= form.select :subject_id, options_for_select(@subjects.map{|sub| [sub.subject_name,sub.id]}) %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/results/_subjectresults.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Subject: <%= title %></h3>
  </div>
  <div class="panel-body">
  <table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
      <th>First Name</th>
      <th>Surname</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% results.each do |result| %>
      <tr>
        <td><%= result.student.name %></td>
        <td><%= result.student.surname %></td>
        <td><%= result.score %></td>
        <td><%= link_to 'Show', result, class: "btn btn-info" %></td>
        <td><%= link_to 'Edit', edit_result_path(result), class: "btn btn-success" %></td>
        <td><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
<% end %>
  </tbody>
</table>
</div>
</div>

app/views/results/edit.html.erb
<h1>Editing Result</h1>

<%= render 'form', result: @result %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Results</h1>
  <%= render 'subjectresults', results:  @result_english, title: 'English' %>
  
  <%= render 'subjectresults', results:  @result_math, title: 'Maths' %>
<br>

<%= link_to 'New Result', new_result_path, class: "btn btn-success" %>

app/views/results/new.html.erb
<h1>New Result</h1>

<%= render 'form', result: @result %>

<%= link_to 'Back', results_path %>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Score:</strong>
  <%= @result.score %>
</p>

<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', results_path %>

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form class="form-horizontal">
    <fieldset>
      <div class="form-group">
        <label for="inputName" class="col-lg-2 control-label">Student Name</label>
        <div class="col-lg-10">
          <%= form.text_field :name, id: :student_name %>
        </div>
      </div>
        <div class="form-group">
        <label for="inputName" class="col-lg-2 control-label">Student Surname</label>
        <div class="col-lg-10">
          <%= form.text_field :surname, id: :student_surname %>
        </div>
      </div>
        <div class="form-group">
        <label for="inputName" class="col-lg-2 control-label">Student Code</label>
        <div class="col-lg-10">
          <%= form.text_field :student_code, id: :student_student_code %>
        </div>
      </div>
    </fieldset>
    <div class="actions">
      <%= form.submit %>
    </div>
  </form>

<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Student code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.surname %></td>
        <td><%= student.student_code %></td>
        <td><%= link_to 'Show', student, class: "btn btn-info" %></td>
        <td><%= link_to 'Edit', edit_student_path(student), class: "btn btn-success" %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path, class: "btn btn-success" %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @student.surname %>
</p>

<p>
  <strong>Student code:</strong>
  <%= @student.student_code %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

app/views/subjects/_form.html.erb
<%= form_with(model: subject, local: true) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <form class="form-horizontal">
    <fieldset>
      <div class="form-group">
        <label for="inputName" class="col-lg-2 control-label">Subject Name</label>
        <div class="col-lg-10">
            <%= form.text_field :name, id: :subject_name %>
        </div>
      </div>
        <div class="form-group">
        <label for="inputName" class="col-lg-2 control-label">Subject Code</label>
        <div class="col-lg-10">
          <%= form.text_field :subject_code, id: :subject_subject_code %>
        </div>
      </div>
    </fieldset>
    <div class="actions">
      <%= form.submit %>
    </div>
  </form>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subjects</h1>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Subject code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.name %></td>
        <td><%= subject.subject_code %></td>
        <td><%= link_to 'Show', subject, class: "btn btn-info" %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject), class: "btn btn-success" %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject', new_subject_path, class: "btn btn-success" %>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subject.name %>
</p>

<p>
  <strong>Subject code:</strong>
  <%= @subject.subject_code %>
</p>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>